Add Python 3.7 and Django 1.11 to the build matrix
Fixes #1125.

Requires pinning mysqlclient<1.4 because of mysqlclient's failure to
interpolate named params into an SQL query (it converts strings to bytes
and afterwards complains that it cannot find b"first_name", e.g. in
test_raw_query_param_conversion:

  ...
  File "/home/travis/build/jazzband/django-debug-toolbar/.tox/mariadb/lib/python3.7/site-packages/MySQLdb/cursors.py", line 188, in execute
    query = query % args
  KeyError: b'first_name'