Update installation.rst
I tried using django-debug-toolbar with Django 1.7b1.

At first, I configured just like documentation (add `'debug_toolbar.apps.DebugToolbarConfig'` to `INSTALLED_APPS`) and I failed to runserver because 

```
ImportError: No module named DebugToolbarConfig
```

Next, I configured as before 1.6 (add `'debug_toolbar'` to `INSTALLED_APPS`) and I succeeded in runserver.