Fix toggling of table rows in the profiling panel UI
Fixes JS error. The error in Firefox was:

    TypeError: container is null

        init http://localhost:8000/static/debug_toolbar/js/toolbar.js:147
        on http://localhost:8000/static/debug_toolbar/js/toolbar.js:7